spring:
  redis:
    database: 76
    host: r-bp1d54c22cd42cc4pd.redis.rds.aliyuncs.com
    port: 6379
    password: Tzq@redis
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    timeout: 5000

logging:
  file:
    path: payment
  config: classpath:logback.groovy